export const PARAM_IS_NOT_OBJECT = 'PARAM_IS_NOT_OBJECT';
export const PARAM_IS_REQUIRED = 'PARAM_IS_REQUIRED';
export const PARAM_IS_NOT_DEFINED = 'PARAM_IS_NOT_DEFINED';
export const PARAM_IS_NOT_EMAIL = 'PARAM_IS_NOT_EMAIL';
export const PARAM_IS_NOT_NUMBER = 'PARAM_IS_NOT_NUMBER';

export const PARAM_IS_ABOVE = 'PARAM_IS_ABOVE';
export const PARAM_IS_BELOW = 'PARAM_IS_BELOW';
export const PARAM_IS_NOT_ONE_OF = 'PARAM_IS_NOT_ONE_OF';
export const PARAM_IS_NOT_EMPTY = 'PARAM_IS_NOT_EMPTY';
export const PARAM_IS_NOT_ARRAY = 'PARAM_IS_NOT_ARRAY';