module.exports = {
    PARAM_IS_NOT_OBJECT: 'IS_NOT_OBJECT',
    PARAM_IS_REQUIRED: 'PARAM_IS_REQUIRED',
    PARAM_IS_NOT_STRING: 'PARAM_IS_NOT_STRING',
    PARAM_IS_NOT_EMAIL: 'PARAM_IS_NOT_EMAIL',
    PARAM_IS_NOT_NUMBER: 'PARAM_IS_NOT_NUMBER',
    
    PARAM_IS_ABOVE: 'PARAM_IS_ABOVE',
    PARAM_IS_BELOW: 'PARAM_IS_BELOW'
};