export const PARAM_IS_NOT_OBJECT = 'PARAM_IS_NOT_OBJECT';
export const PARAM_IS_REQUIRED = 'PARAM_IS_REQUIRED';
export const PARAM_IS_NOT_STRING = 'PARAM_IS_NOT_STRING';
export const PARAM_IS_NOT_EMAIL = 'PARAM_IS_NOT_EMAIL';
export const PARAM_IS_NOT_NUMBER = 'PARAM_IS_NOT_NUMBER';

export const PARAM_IS_ABOVE = 'PARAM_IS_ABOVE';
export const PARAM_IS_BELOW = 'PARAM_IS_BELOW';